[package]
name = "minecraft-server-proxy"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "minecraft-server-proxy"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
